# Generated by Django 3.1.5 on 2021-02-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionconsumed',
            name='produced_consumed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.productionproduced'),
            preserve_default=False,
        ),
    ]
